### ISSUE TITLE
Simplify building in dev watch mode

### ISSUE THREAD

**Issue by jednano** [jedmao/react-bem#14]
Currently, you need to run two separate processes:
- `npm run build:watch`
- `npm run watch`

This is very dirty, it causes multiple rebuilds sometimes and it even causes vscode to crash (sometimes).

Figure out a way to simplify the build so there's only one watch command to run. Perhaps https://github.com/kulshekhar/ts-jest will work.

**Comment by bjdelro** [comment]
@jedmao Able to run `npm run watch` without having to run `npm run build:watch` before, this seems to be a non-issue.

**Comment by jednano** [comment]
Awesome! I was unable to reproduce as well. Not sure what I was doing before. Thanks!
