### ISSUE TITLE
Prop Name Collision

### ISSUE THREAD

**Issue by Intregrisist** [jedmao/react-bem#26]
**Version:** 0.3.0

**Issue:**
The `block`, `element`, `modifiers` prop names are too common that they cause collision with other typed component libraries, such as [`react-bootstrap`](https://github.com/react-bootstrap/react-bootstrap). Therefore, we had suggested that we prefix the prop names a bit to reduce the chances of collision: `bemBlock`, `bemElement`, and `bemModifiers`

**Code**

Error when compiling code:

```
ERROR in [at-loader] ./node_modules/@types/react-bootstrap/lib/Button.d.ts:5:22 
    TS2430: Interface 'ButtonProps' incorrectly extends interface 'HTMLProps<Button>'.
  Types of property 'block' are incompatible.
    Type 'boolean' is not assignable to type 'string'.

ERROR in [at-loader] ./node_modules/@types/react-bootstrap/lib/ButtonGroup.d.ts:5:22 
    TS2430: Interface 'ButtonGroupProps' incorrectly extends interface 'HTMLProps<ButtonGroup>'.
  Types of property 'block' are incompatible.
    Type 'boolean' is not assignable to type 'string'.

ERROR in [at-loader] ./node_modules/@types/react-bootstrap/lib/ButtonToolbar.d.ts:5:22 
    TS2430: Interface 'ButtonToolbarProps' incorrectly extends interface 'HTMLProps<ButtonToolbar>'.
  Types of property 'block' are incompatible.
    Type 'boolean' is not assignable to type 'string'.
```

**Expected behavior:**

No Typescript issues.

**Actual behavior:**

Error

**Comment by jednano** [comment]
This makes sense. The `block`, `element` and `modifiers` props were clearly a bit too generic for use with other 3rd-party packages. Will submit a PR to update these names.
